# Generated by Django 3.1.4 on 2023-09-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADM',
            fields=[
                ('id_adm', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('senha', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ecossistema',
            fields=[
                ('id_eco', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Foruns',
            fields=[
                ('id_foruns', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('id_instituicao', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaAmbiental',
            fields=[
                ('id_problema_amb', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacoes',
            fields=[
                ('id_publi', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes_admin', to='cleanUpSite.adm')),
                ('forunz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes_foruns', to='cleanUpSite.foruns')),
                ('id_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanUpSite.adm')),
                ('id_foruns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanUpSite.foruns')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('senha', models.CharField(max_length=6)),
                ('data_cadastro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPubli',
            fields=[
                ('id_userpubli', models.AutoField(primary_key=True, serialize=False)),
                ('data_interacao', models.DateTimeField()),
                ('id_publi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanUpSite.publicacoes')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanUpSite.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='UserFor',
            fields=[
                ('id_userfor', models.AutoField(primary_key=True, serialize=False)),
                ('data_participacao', models.DateTimeField()),
                ('id_foruns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanUpSite.foruns')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanUpSite.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('id_instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanUpSite.instituicao')),
            ],
        ),
    ]
