# Generated by Django 3.1.4 on 2023-09-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanUpSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacoes',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='publicacoes',
            name='forunz',
        ),
    ]
