# Generated by Django 3.1.4 on 2023-09-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanUpSite', '0003_remove_usuarios_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foruns',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
    ]
