# Generated by Django 3.1.4 on 2023-09-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanUpSite', '0004_auto_20230930_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foruns',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
    ]
