# Generated by Django 3.1.4 on 2023-10-26 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleanUpSite', '0005_auto_20230930_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfor',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='userfor',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
