# Generated by Django 3.1.4 on 2023-10-27 00:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cleanUpSite', '0006_auto_20231026_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfor',
            name='data_participacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 0, 12, 18, 254676, tzinfo=utc)),
        ),
    ]
