# Generated by Django 3.1.4 on 2023-10-27 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cleanUpSite', '0007_auto_20231026_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfor',
            name='data_participacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 0, 16, 38, 803466, tzinfo=utc)),
        ),
    ]
