# Generated by Django 3.1.4 on 2023-10-27 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cleanUpSite', '0008_auto_20231026_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfor',
            name='data_participacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
