# Generated by Django 3.1.4 on 2023-11-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanUpSite', '0011_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoTIFF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo_geotiff', models.FileField(upload_to='geotiffs/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
